In [245]:
import pandas as pd

df = pd.read_csv(r"D:\Loan_approval\loan_approval_dataset.csv")

In [246]:
df = df.drop_duplicates()
df.columns = df.columns.str.strip().str.lower()

In [247]:
import numpy as np

num_col = df.select_dtypes(include="number").columns

df[num_col] = df[num_col].mask(df[num_col] < 0, np.nan)

In [248]:
cat_col = df.select_dtypes(include=["string", "category", "object"]).columns

for col in cat_col:
    df[col] = df[col].str.strip().str.lower()

In [249]:
from sklearn.model_selection import train_test_split

unnecessary_col = ["loan_id", "loan_status"]

X = df.drop(unnecessary_col, axis=1)
y = df["loan_status"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [250]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [251]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler

In [252]:
numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", MinMaxScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

In [253]:
numeric_col = X_train.select_dtypes(include="number").columns
categorical_col = X_train.select_dtypes(include=["string", "object", "category"]).columns

In [254]:
preprocessor = ColumnTransformer([
    ("num", numerical_pipeline, numeric_col),
    ("cat", categorical_pipeline, categorical_col)
])

In [255]:
from sklearn.linear_model import LogisticRegression

model_LR = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(random_state=42))
])

In [256]:
model_LR.fit(X_train, y_train)

y_pred_LR = model_LR.predict(X_test)

In [257]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_LR), 4))
print("Precision Score : ",round(precision_score(y_test, y_pred_LR), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_LR), 4))
print("F1 Score : ", f1_score(y_test, y_pred_LR))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_LR))
print("Classification Report : ",classification_report(y_test, y_pred_LR))

Accuracy Score :  0.9251
Precision Score :  0.9246
Recall Score :  0.8731
F1 Score :  0.8980891719745223
Confusion Matrix:
[[508  23]
 [ 41 282]]
Classification Report :                precision    recall  f1-score   support

           0       0.93      0.96      0.94       531
           1       0.92      0.87      0.90       323

    accuracy                           0.93       854
   macro avg       0.92      0.91      0.92       854
weighted avg       0.93      0.93      0.92       854



In [258]:
from sklearn.neighbors import KNeighborsClassifier

model_KNN = Pipeline([
    ("preprocessor", preprocessor),
    ("model", KNeighborsClassifier(n_neighbors=5))
])

In [259]:
model_KNN.fit(X_train, y_train)

y_pred_KNN = model_KNN.predict(X_test)

In [260]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_KNN),4))
print("Precision Score : ", round(precision_score(y_test, y_pred_KNN), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_KNN), 4))
print("F1 Score : ", f1_score(y_test, y_pred_KNN))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_KNN))
print("Classification Report : ",classification_report(y_test, y_pred_KNN))

Accuracy Score :  0.9052
Precision Score :  0.8903
Recall Score :  0.8545
F1 Score :  0.8720379146919431
Confusion Matrix:
[[497  34]
 [ 47 276]]
Classification Report :                precision    recall  f1-score   support

           0       0.91      0.94      0.92       531
           1       0.89      0.85      0.87       323

    accuracy                           0.91       854
   macro avg       0.90      0.90      0.90       854
weighted avg       0.90      0.91      0.90       854



In [261]:
from sklearn.tree import DecisionTreeClassifier

model_DT = Pipeline([
    ("preprocessor", preprocessor),
    ("model", DecisionTreeClassifier(random_state=42))
])

In [262]:
model_DT.fit(X_train, y_train)

y_pred_DT = model_DT.predict(X_test)

In [263]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_DT), 4))
print("Precision Score : ", round(precision_score(y_test, y_pred_DT), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_DT), 4))
print("F1 Score : ", f1_score(y_test, y_pred_DT))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_DT))
print("Classification Report : ",classification_report(y_test, y_pred_DT))

Accuracy Score :  0.9719
Precision Score :  0.9687
Recall Score :  0.9567
F1 Score :  0.9626168224299065
Confusion Matrix:
[[521  10]
 [ 14 309]]
Classification Report :                precision    recall  f1-score   support

           0       0.97      0.98      0.98       531
           1       0.97      0.96      0.96       323

    accuracy                           0.97       854
   macro avg       0.97      0.97      0.97       854
weighted avg       0.97      0.97      0.97       854



In [264]:
from sklearn.ensemble import RandomForestClassifier

model_RFC = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(n_estimators=100, random_state=42))
])

In [265]:
model_RFC.fit(X_train, y_train)

y_pred_RFC = model_RFC.predict(X_test)

In [266]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_RFC), 4))
print("Precision Score : ", round(precision_score(y_test, y_pred_RFC), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_RFC), 4))
print("F1 Score : ", f1_score(y_test, y_pred_RFC))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_RFC))
print("Classification Report : ",classification_report(y_test, y_pred_RFC))

Accuracy Score :  0.9813
Precision Score :  0.9873
Recall Score :  0.9628
F1 Score :  0.9749216300940439
Confusion Matrix:
[[527   4]
 [ 12 311]]
Classification Report :                precision    recall  f1-score   support

           0       0.98      0.99      0.99       531
           1       0.99      0.96      0.97       323

    accuracy                           0.98       854
   macro avg       0.98      0.98      0.98       854
weighted avg       0.98      0.98      0.98       854



In [267]:
from sklearn.svm import SVC

model_SVC = Pipeline([
    ("preprocessor", preprocessor),
    ("model", SVC(random_state=42))
])

In [268]:
model_SVC.fit(X_train, y_train)

y_pred_SVC = model_SVC.predict(X_test)

In [269]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_SVC), 4))
print("Precision Score : ", round(precision_score(y_test, y_pred_SVC), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_SVC), 4))
print("F1 Score : ", f1_score(y_test, y_pred_SVC))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_SVC))
print("Classification Report : ",classification_report(y_test, y_pred_SVC))

Accuracy Score :  0.9415
Precision Score :  0.9306
Recall Score :  0.9133
F1 Score :  0.921875
Confusion Matrix:
[[509  22]
 [ 28 295]]
Classification Report :                precision    recall  f1-score   support

           0       0.95      0.96      0.95       531
           1       0.93      0.91      0.92       323

    accuracy                           0.94       854
   macro avg       0.94      0.94      0.94       854
weighted avg       0.94      0.94      0.94       854



In [270]:
from xgboost import XGBClassifier

model_XGB = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBClassifier(random_state=42))
])

In [271]:
model_XGB.fit(X_train, y_train)

y_pred_XGB = model_XGB.predict(X_test)

In [272]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report, confusion_matrix, f1_score

print("Accuracy Score : ", round(accuracy_score(y_test, y_pred_XGB), 4))
print("Precision Score : ", round(precision_score(y_test, y_pred_XGB), 4))
print("Recall Score : ", round(recall_score(y_test, y_pred_XGB), 4))
print("F1 Score : ", f1_score(y_test, y_pred_XGB))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_XGB))
print("Classification Report : ",classification_report(y_test, y_pred_XGB))

Accuracy Score :  0.9801
Precision Score :  0.9842
Recall Score :  0.9628
F1 Score :  0.97339593114241
Confusion Matrix:
[[526   5]
 [ 12 311]]
Classification Report :                precision    recall  f1-score   support

           0       0.98      0.99      0.98       531
           1       0.98      0.96      0.97       323

    accuracy                           0.98       854
   macro avg       0.98      0.98      0.98       854
weighted avg       0.98      0.98      0.98       854



In [273]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model_RFC,      
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("Cross Validation Scores:", scores)
print("Mean CV Accuracy:", scores.mean())

Cross Validation Scores: [0.98009368 0.97775176 0.98711944 0.97775176 0.98007034]
Mean CV Accuracy: 0.9805573935222428


In [274]:
features = model_RFC.named_steps["preprocessor"].get_feature_names_out()
importance = model_RFC.named_steps["model"].feature_importances_

for feature, score in zip(features, importance):
    print(feature, score)

num__no_of_dependents 0.009388070761041726
num__income_annum 0.018993097574885345
num__loan_amount 0.03042554887824358
num__loan_term 0.0633586498442268
num__cibil_score 0.7964275269232416
num__residential_assets_value 0.018300898979393486
num__commercial_assets_value 0.018023087812705913
num__luxury_assets_value 0.019239383694998505
num__bank_asset_value 0.017076660651933293
cat__education_graduate 0.00224497776650108
cat__education_not graduate 0.001895117909031587
cat__self_employed_no 0.0023117281897418623
cat__self_employed_yes 0.002315251014055177


In [275]:
accuracy_LR = accuracy_score(y_test, y_pred_LR)

accuracy_KNN = accuracy_score(y_test, y_pred_KNN)

accuracy_DT = accuracy_score(y_test, y_pred_DT)

accuracy_RFC = accuracy_score(y_test, y_pred_RFC)

accuracy_SVC = accuracy_score(y_test, y_pred_SVC)

accuracy_XGB = accuracy_score(y_test, y_pred_XGB)

In [276]:
import pandas as pd

accuracy_df = pd.DataFrame({
    "Algorithm": [
        "Logistic Regression",
        "KNN",
        "Decision Tree",
        "Random Forest",
        "SVC",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_LR,
        accuracy_KNN,
        accuracy_DT,
        accuracy_RFC,
        accuracy_SVC,
        accuracy_XGB
    ]
})

accuracy_df.sort_values(by="Accuracy", ascending=False)

,Algorithm,Accuracy
3,Random Forest,0.981265
5,XGBoost,0.980094
2,Decision Tree,0.971897
4,SVC,0.941452
0,Logistic Regression,0.925059
1,KNN,0.905152


In [277]:
print("Final Model Selected: Random Forest Classifier")

Final Model Selected: Random Forest Classifier


In [278]:
import joblib

joblib.dump(model_RFC, "loan_approval_final_model.pkl")

['loan_approval_final_model.pkl']